# miro_export — declare a schema that's compiled, then walked at build
# time to emit generated artifacts.
#
# Produces one user-facing target plus one helper:
#
#   ${NAME}              INTERFACE library carrying the generated header
#                        include dirs. Linking it gives a consumer the
#                        typed wrappers.
#
#   ${NAME}_Codegen      Build-time executable that walks the listed API
#                        classes via codegenMain<...>(). Each
#                        miro_export_emit() call appends a POST_BUILD step
#                        that re-runs the exec to emit one set of files.
#                        Consumers add_dependencies() against it so the
#                        exec — and its POST_BUILD emits — fire before the
#                        consumer compiles.
#
# Single-call shortcut: pass OUTPUT_DIR + FORMATS to miro_export() and an
# emit step is added implicitly. Call miro_export_emit() afterwards for
# additional emits (e.g. cpp headers into a different directory).
#
# Usage:
#
#   miro_export(MySchema
#       API_HEADER Api/TodoApi.h        # one or more headers declaring the APIs
#       API Api::Todos [Api::Other]     # fully-qualified API class(es)
#       [OUTPUT_DIR ...] [OUTPUT_NAME ...] [FORMATS ...])
#
# The user declares one or more API classes with a `void reflect(Miro::
# ApiReflector&)` method. miro_export generates a small stub main:
#
#   #include <Miro/Miro.h>
#   #include "<API_HEADER>"            // each header passed via API_HEADER
#   int main(int argc, char** argv)
#   {
#       return Miro::TypeExport::codegenMain<Api::Todos[, ...]>(argc, argv);
#   }
function(miro_export NAME)
    set(oneValueArgs OUTPUT_DIR OUTPUT_NAME)
    set(multiValueArgs FORMATS API API_HEADER)
    cmake_parse_arguments(ME "" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if (NOT ME_API)
        message(FATAL_ERROR
                "miro_export(${NAME}): API is required")
    endif ()
    if (NOT ME_API_HEADER)
        message(FATAL_ERROR
                "miro_export(${NAME}): API_HEADER is required")
    endif ()

    add_library(${NAME} INTERFACE)

    # The codegen executable runs as a build-time tool on the host. When
    # cross-compiling there's no way to run a foreign-arch executable on
    # the build machine, so we skip creating it — caller-side
    # add_dependencies(consumer ${NAME}_Codegen) becomes a no-op and
    # the project links against committed generated files.
    if (CMAKE_CROSSCOMPILING)
        return()
    endif ()

    # Resolve API_HEADER paths so the generated stub's #include lines
    # work from the build directory.
    set(absHeaders "")
    foreach (hdr IN LISTS ME_API_HEADER)
        if (IS_ABSOLUTE "${hdr}")
            list(APPEND absHeaders "${hdr}")
        else ()
            list(APPEND absHeaders "${CMAKE_CURRENT_SOURCE_DIR}/${hdr}")
        endif ()
    endforeach ()

    # Generate stub_main.cpp: includes each API header, then dispatches
    # to codegenMain<...> with the user's API class list. file(WRITE)
    # is configure-time; the stub depends only on configure inputs so
    # this is correct (a rebuild is triggered if any of those change).
    #
    # Semicolons are escaped (\;) because CMake treats unescaped `;`
    # inside strings as list separators — they'd get eaten otherwise
    # and the emitted C++ wouldn't compile.
    set(stub "${CMAKE_CURRENT_BINARY_DIR}/${NAME}_codegen_main.cpp")
    set(stubBody
            "// Generated by miro_export(${NAME}). Do not edit.\n")
    set(stubBody "${stubBody}#include <Miro/Miro.h>\n")
    foreach (hdr IN LISTS absHeaders)
        set(stubBody "${stubBody}#include \"${hdr}\"\n")
    endforeach ()
    list(JOIN ME_API ", " apiTypeList)
    set(stubBody "${stubBody}\nint main(int argc, char** argv)\n")
    set(stubBody "${stubBody}{\n")
    set(stubBody
            "${stubBody}    return Miro::TypeExport::codegenMain<${apiTypeList}>(argc, argv)\;\n")
    set(stubBody "${stubBody}}\n")
    file(WRITE ${stub} ${stubBody})

    add_executable(${NAME}_Codegen
            ${stub}
            $<TARGET_OBJECTS:MiroFormats>
            $<TARGET_OBJECTS:MiroCodegenWriter>)
    target_link_libraries(${NAME}_Codegen
            PRIVATE Miro MiroFormats MiroCodegenWriter)

    if (TARGET miro_warnings)
        target_link_libraries(${NAME}_Codegen PRIVATE miro_warnings)
    endif ()

    if (ME_OUTPUT_DIR)
        miro_export_emit(${NAME}
                OUTPUT_DIR ${ME_OUTPUT_DIR}
                OUTPUT_NAME ${ME_OUTPUT_NAME}
                FORMATS ${ME_FORMATS})
    endif ()
endfunction()


# miro_export_emit — register a generation step on a schema declared via
# miro_export(). Each emit attaches a POST_BUILD command to the schema's
# codegen executable, so every emit reruns whenever the exec is rebuilt
# (i.e. whenever any registration source changes).
#
# Usage:
#   miro_export_emit(MySchema
#       OUTPUT_DIR  <dir>
#       OUTPUT_NAME <stem>           # optional; defaults to schema target name
#       FORMATS     ts backend ...)  # optional; defaults to all
function(miro_export_emit NAME)
    cmake_parse_arguments(MEE "" "OUTPUT_DIR;OUTPUT_NAME" "FORMATS" ${ARGN})

    if (NOT MEE_OUTPUT_DIR)
        message(FATAL_ERROR "miro_export_emit(${NAME}): OUTPUT_DIR is required")
    endif ()
    if (NOT TARGET ${NAME})
        message(FATAL_ERROR
                "miro_export_emit(${NAME}): target does not exist; "
                "call miro_export(${NAME} ...) first")
    endif ()
    if (NOT MEE_OUTPUT_NAME)
        set(MEE_OUTPUT_NAME ${NAME})
    endif ()

    target_include_directories(${NAME} INTERFACE ${MEE_OUTPUT_DIR})
    file(MAKE_DIRECTORY "${MEE_OUTPUT_DIR}")

    if (CMAKE_CROSSCOMPILING)
        return()
    endif ()

    set(formatArgs "")
    foreach (fmt IN LISTS MEE_FORMATS)
        list(APPEND formatArgs --format ${fmt})
    endforeach ()

    add_custom_command(TARGET ${NAME}_Codegen POST_BUILD
            COMMAND ${NAME}_Codegen
                    --out ${MEE_OUTPUT_DIR}
                    --name ${MEE_OUTPUT_NAME}
                    ${formatArgs}
            COMMENT "Exporting types: ${NAME} -> ${MEE_OUTPUT_DIR}"
            VERBATIM)
endfunction()
